services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: articles-scraper
    environment:
      - PORT=3000
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
  mysql:
    image: mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysqldb:/var/lib/mysql
volumes:
  mysqldb: